### ISSUE TITLE
Add sass-lint to improve scss style

### ISSUE THREAD

**Issue by xf-** [threema-ch/threema-web#31]
In general the scss files are nice, but detail is inconstant.

Examples:
```scss
spaces behind comma or not
$material-grey: rgba(0, 0, 0, 0.54);
$material-card-shadow: 0px 2px 5px 0px rgba(0,0,0,0.16),0px 2px 5px 0px rgba(0,0,0,0.23);

hardcoded color (available as variable)
$bright-background-color: white;
#main {
    background-color: white;
}
```
- Comment out code
- empty selectors
- 0px value vs. 0 without px.
- one selector vs multiple per line
- lowercase vs. uppercase hex colors
- different comment style /* */ vs //
